# Generated by Django 2.1 on 2019-12-06 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('correction_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='cat_desc',
            field=models.TextField(blank=True, verbose_name='Category Description'),
        ),
        migrations.AlterField(
            model_name='category',
            name='cat_name',
            field=models.CharField(max_length=50, verbose_name='Category Name'),
        ),
        migrations.AlterField(
            model_name='post',
            name='pst_img',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Post Image'),
        ),
        migrations.AlterField(
            model_name='post',
            name='pst_title',
            field=models.CharField(max_length=150, verbose_name='Post Title'),
        ),
    ]
