# Generated by Django 2.1 on 2019-12-06 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('correction_app', '0002_auto_20191206_1127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='pst_img',
            field=models.ImageField(blank=True, null=True, upload_to='img_uploads', verbose_name='Post Image'),
        ),
    ]
