# Generated by Django 2.1 on 2019-12-09 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('correction_app', '0003_auto_20191206_1159'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abt_title', models.CharField(max_length=160, verbose_name='About Us')),
                ('abt_img', models.ImageField(blank=True, upload_to='img_uploads', verbose_name='About Image')),
                ('abt_content', models.TextField(blank=True, verbose_name='About Content')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('srv_title', models.CharField(max_length=150, verbose_name='Service Title')),
                ('srv_content', models.TextField(blank=True, verbose_name='Service Content')),
            ],
        ),
    ]
