# Generated by Django 2.1 on 2019-12-09 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('correction_app', '0004_about_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='abt_title',
            field=models.CharField(max_length=160, verbose_name='Member Name'),
        ),
    ]
